#!/bin/sh -e
#**************************************************************************
#*                                                                        *
#*                                 OCaml                                  *
#*                                                                        *
#*            David Allsopp, University of Cambridge & Tarides            *
#*                                                                        *
#*   Copyright 2025 David Allsopp Ltd.                                    *
#*                                                                        *
#*   All rights reserved.  This file is distributed under the terms of    *
#*   the GNU Lesser General Public License version 2.1, with the          *
#*   special exception on linking described in the file LICENSE.          *
#*                                                                        *
#**************************************************************************

# This script is called from the root of the repository at the end of
# `make INSTALL_MODE=opam install` and is responsible for converting the various
# files generated by the opam installation backend into a .install file and a
# -fixup.sh script.
# Parameters are the following Makefile variables:
#   $1 = $(OPAM_PACKAGE_NAME)
#   $2 = $(UNIX_OR_WIN32)
#   $3 = $(LN)

# The opam packaging for the compiler installs config.cache and config.status
# (when building with opam, it is required to have configure with -C).
# config.cache is installed in order to speed-up the legacy `make reconfigure`
# and config.status is installed in order to allow the source-tree to be
# re-configured the autoconf way.
cat > opam-share <<"EOF"
"config.cache" {"ocaml/config.cache"}
"config.status" {"ocaml/config.status"}
EOF

# Generate the .install file
for section in bin lib_root libexec_root man share_root; do
  file="opam-${section%_root}"
  if [ -e "$file" ]; then
    echo "$section: ["
    sed -e 's/^/  /' "$file"
    echo ']'
    rm -f "$file"
  fi
done > "$1.install"

{
  echo '#!/bin/sh'
  echo 'set -eu'
  for fileset in clone-*; do
    # There isn't a portable way to test that a glob doesn't match, hence the
    # redundant-appearing `test -f` (if there are no matches, some shells will
    # not execute the loop at all - which is what we want. Some shells will
    # instead run the loop once with `fileset='clone-*'`)
    if [ -f "$fileset" ]; then
      dir="$(echo "${fileset#clone-}" | sed -e 's|@|/|g')"
      echo 'mkdir -p "$1"'"'/$dir'"
      sed -e 's|\(.*\) \(.*\)|cp '"'\\1'"' "$1"'"'/$dir/\\2'|" "$fileset"
    fi
  done
  rm -f clone-*
  if [ -f create-symlinks ]; then
    echo 'cd "$1"'
    # opam runs this script _before_ processing the .install file, which means
    # that only the root switch directories will exist (in particular, lib/ocaml
    # will not yet have been created). This incantation creates any required
    # subdirectories. On Windows, create-symlinks will only have been used if
    # symbolic links are available, and we never symlink directories. We use
    # mklink, as that allows symlinks to files which don't exist yet to be
    # created on Windows (where `CYGWIN=winsymlinks:nativestrict ln -s` can't)
    cut -f 1 -d ' ' create-symlinks | sort -u | sed -ne "s|.*/.*|mkdir -p '&'|p"
    if [ "$2" = 'win32' ]; then
      echo 'cmd /c "mklink __ln_test mklink-test"'
      echo 'if test -L "$1/__ln_test"; then'
      sed -e 's|\(.*\) \(.*\) \(.*\)|mklink \1/\3 \2|' \
          -e 's|/|\\\\|g' \
          -e 's|.*|  cmd /c "&"|' create-symlinks
      echo 'else'
      sed -e 's|\(.*\) \(.*\) \(.*\)|  $CP '"'\\1/\\2' '\\1/\\3'|" \
               create-symlinks
      echo 'fi'
      echo 'rm -f __ln_test'
    else
      sed -e 's|\(.*\) \(.*\) \(.*\)|'"$3 '\\2' '\\1/\\3'|" create-symlinks
    fi
    rm create-symlinks
  fi
} > "$1-fixup.sh"
