#!/bin/sh -e
#**************************************************************************
#*                                                                        *
#*                                 OCaml                                  *
#*                                                                        *
#*            David Allsopp, University of Cambridge & Tarides            *
#*                                                                        *
#*   Copyright 2025 David Allsopp Ltd.                                    *
#*                                                                        *
#*   All rights reserved.  This file is distributed under the terms of    *
#*   the GNU Lesser General Public License version 2.1, with the          *
#*   special exception on linking described in the file LICENSE.          *
#*                                                                        *
#**************************************************************************

# This script is called from the root of the repository at the end of
# `make INSTALL_MODE=clone install` and is responsible for converting the
# various files generated by the clone installation backend into a -clone.sh
# script.
# Parameters are the following Makefile variables:
#   $1 = $(OPAM_PACKAGE_NAME)
#   $2 = $(UNIX_OR_WIN32)
#   $3 = $(LN)

if [ -e config.cache ]; then
  echo 'share/ocaml/config.cache' > clone-share@ocaml
fi

{
  cat <<"EOF"
#!/bin/sh
set -e
mkdir -p "$1"
echo 'ln -f "$@" "$dest/"' > "$1/clone-files"
EOF
  for fileset in clone-*; do
    dir="$(echo "${fileset#clone-}" | sed -e 's|@|/|g')"
    echo 'mkdir -p "$1/'"$dir"'"'
    echo 'dest="$1/'"$dir"'" xargs sh "$1/clone-files" <<"EOF"'
    cat "$fileset"
    echo 'EOF'
  done
  rm -f clone-*
  # ld.conf is a configuration file, so is always copied. Makefile.config and
  # config.status will both contain the original prefix, which must be updated.
  if [ ! -e config.cache ]; then
    echo 'mkdir -p "$1/share/ocaml"'
  fi
  cat <<"EOF"
cp lib/ocaml/ld.conf "$1/lib/ocaml/ld.conf"
cat > "$1/prefix.awk" <<"ENDAWK"
{
  rest = $0
  while ((p = index(rest, ENVIRON["O"]))) {
    printf "%s%s", substr(rest, 1, p-1), ENVIRON["N"]
    rest = substr(rest, p + length(ENVIRON["O"]))
  }
  print rest
}
ENDAWK
prefix="$(sed -ne 's/^prefix *= *//p' lib/ocaml/Makefile.config)"
for file in lib/ocaml/Makefile.config share/ocaml/config.status; do
  O="$prefix" N="$1" awk -f "$1/prefix.awk" "$file" > "$1/$file"
done
rm -f "$1/clone-files" "$1/prefix.awk"
EOF
  if [ -f create-symlinks ]; then
    echo 'cd "$1"'
    if [ "$2" = 'win32' ]; then
      sed -e 's|\(.*\) \(.*\) \(.*\)|mklink \1/\3 \2|' \
          -e 's|/|\\|g' \
          -e 's|.*|cmd /c "&"|' create-symlinks
    else
      sed -e 's|\(.*\) \(.*\) \(.*\)|'"$3"' \2 \1/\3|' create-symlinks
    fi
    rm create-symlinks
  fi
} > "$1-clone.sh"
