name: Build with MSVC

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

on:
  push:
    branches:
      - '4.**'
      - '5.**'
      - 'trunk'
  pull_request:

env:
  BOOTSTRAP_FLEXDLL: true

jobs:
  build:
    permissions: {}

    runs-on: windows-2019

    timeout-minutes: 60

    name: ${{ matrix.x86_64 && 'MSVC 64 bits' || 'MSVC 32 bits' }}

    strategy:
      fail-fast: false
      matrix:
        x86_64: [true, false]

    steps:

      - name: Fetch OCaml
        uses: actions/checkout@v4
        with:
          submodules: true

      - name: Install Cygwin
        uses: cygwin/cygwin-install-action@v3
        with:
          packages: make,bash,mingw64-x86_64-gcc-core,mingw64-i686-gcc-core
          install-dir: 'D:\cygwin'

      - name: Build OCaml
        shell: cmd
        env:
          HOST: ${{ matrix.x86_64 && 'x86_64-w64-mingw32' || 'i686-w64-mingw32' }}
        run: >-
           tools\ci\appveyor\gha_build.cmd install
           tools\ci\appveyor\gha_build.cmd build
